### ISSUE TITLE
Escaped characters

### ISSUE THREAD

**Issue by sharnoff** [mk-lang/mk#4]
# Escaped characters

Note: L is the column for whether it is required in string literals to escape that character; C is whether it is required to be escaped in character ranges.

Char | L | C
-- | -- | --
  \|  | N | Y 
  ,  | N | Y 
  '  | N | N 
  "  | Y | N 
 \n  | Y | Y 
 \r  | Y | Y 
 \t  | Y | Y 
 \f  | Y | Y 
 \v  | Y | Y 
 \\  | Y | Y 

Any escaped character may be escaped in either string literals or character ranges, regardless of whether it is required to be. Characters are escaped with a backslash - those in the list that are written above with a backslash will be represented exactly as such.

**Comment by JOT85** [comment]
We should also have C-style hex escape sequences (except for the octal one because it's not nice...)
The syntax should be:
`\xhh` to represent a byte with the numerical value given by `hh` (parsed as hex).
`\uhhhh` the Unicode character with the code point `hhhh` (parsed as hex).
`\Uhhhhhhhh` the Unicode character with the code point `hhhhhhhh` (parsed as hex).

**Comment by JOT85** [comment]
@sharnoff can we close this issue? I'm happy with the syntax escape characters we have here.
